substitutions:
  devicename: esp32-climate
  upper_devicename: esp32-climate
  friendly_name: ...
  hvac_name: HVAC
  global_update_interval: 1min

  # Pinout
  pin_tx:   GPIOXX
  pin_rx:   GPIOYY

esphome:
  name: $devicename
  friendly_name: $friendly_name
  comment: ESP32 controller - HVAC
  on_boot: 
    then:
      switch.turn_on: ir_transmitter_switch_id
preferences:
  flash_write_interval: 
    minutes: 5

esp32:
  board: your board here
  framework:
    type: arduino

external_components:
  source: github://d1mdev/esphome-whirlpool-ac
  components: [whirlpool_ac]
  refresh: 60min

# Logging
logger:
  level: DEBUG
  baud_rate: 0
  logs:
    component: ERROR
    remote.pronto: ERROR

# Enable Home Assistant API
api:
  encryption:
    key: "========================================="

ota:
  - platform: esphome
    password: "======================================"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 120s
  output_power: 10
  power_save_mode: LIGHT

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${devicename} Fallback Hotspot"
    password: "=============="

captive_portal:

remote_receiver:
  id: rcvr_hvac
  pin:
    number: $pin_rx
    inverted: True
    mode:
      input: true
      # pullup: true # use with direct connection between receiver and esp pin
  rmt_channel: 7 # needed for esp32s3 devices
  dump: all
  # high 55% tolerance is recommended for some remote control units, default 25%
  # tolerance: 55%

remote_transmitter:
  pin: $pin_tx
 # Infrared remotes use a 50% carrier signal
  carrier_duty_percent: 50%

button:
  - platform: restart
    name: "Restart"
  - platform: shutdown
    name: "Shutdown"
  - platform: safe_mode
    name: "Restart (Safe Mode)"

binary_sensor:
  - platform: status
    name: "ESP Status"

sensor:
   #external temperature from Home assistant, replace with your own
  - platform: homeassistant
    name: "Room temperature"
    entity_id: sensor.0xxxxxxxxxxxxxx_temperature
    id: room_temperature
    internal: true
    unit_of_measurement: '°C'
    filters:
      - throttle: 1s
      - heartbeat: 30s
      - debounce: 0.5s

# Climate
climate:
  - platform: whirlpool_ac
    id: room_climate
    name: $hvac_name
    receiver_id: rcvr_hvac #set receiver
    sensor: room_temperature #optional - external temperature sensor
    ir_transmitter_switch:
      name: Transmitter
      id: ir_transmitter_switch_id
      restore_mode: ALWAYS_ON
    ifeel_switch:
      name: iFeel
    supports_cool: True
    supports_heat: True
    model: DG11J1-91
    visual:
      min_temperature: 16
      max_temperature: 30
      temperature_step: 1
